fix: cannot find function id in module raydium_cp_swap::create_pool_fee_reveiver
error[E0425]: cannot find function id in module raydium_cp_swap::create_pool_fee_reveiver --> 142 | address= raydium_cp_swap::create_pool_fee_reveiver::id(), | ^^ --> src/lib.rs:40:5


`raydium_cp_swap` crate doesn’t export an id() there (latest version expose only a constant), so we use the ID constant instead!